### ISSUE TITLE
apply_finder_options deprecated in Rails 4

### ISSUE THREAD

**Issue by ffmike** [mislav/will_paginate#322]
If you call will_paginate with AR finder options:

  @suppliers = Suppliers.paginate :order => 'name'

You'll end up with a warning from Rails 4:

  DEPRECATION WARNING: #apply_finder_options is deprecated. (called from paginate at .../lib/will_paginate/active_record.rb:154)

Easily fixable by changing the original call:

  @suppliers = Suppliers.order("name").paginate

The problem is that in Rails 4.1, the original call is going to fail unless the user includes the activerecord_deprecated_finders gem in their project, and this isn't obvious from the error.

Not sure the best way forward here, or I'd submit a PR. I don't think I'd be in favor of will_paginate dragging in activerecord_deprecated_finders itself though. I'd rather have it reject finder options and warn the user to rewrite, but that feels like it might break a lot of existing code.

**Comment by dtwconsulting** [comment]
I am having a hard time trying to understand how to rewrite the following so as not to get this error. In my case I have multiple search fields.  The above only shows a single condition.  Sorry for my lack of knowledge.

My current code is:
@search = Customer.search(params[:q])
@customers = @search.result.paginate(page: params[:page], :per_page => 30, :order => 'last_name ASC')

I get the .order, .limit and .page, just not sure what needs to go into the .where section since there are 3 different fields that can be searched on in the customers.

**Comment by mislav** [comment]
I've dropped use of `apply_finder_options` in master.
