### ISSUE TITLE
Using a route rather than a query string.

### ISSUE THREAD

**Issue by Arcrammer** [mislav/will_paginate#446]
Is this possible? Am I misreading the documentation? So far I've only found out how to change the key of the query string. I'd like to direct users to `/Portfolio/Page/2` rather than `/Portfolio?page=2`.

Everything works fine when I go to `/Portfolio/Page/2`. The problem is that the links output to the view are going to `?page=2` rather than `Page/2`.

Thanks!

**Comment by mislav** [comment]
If there is a `Portfolio/Page/:page` route defined in your application and it takes precedence over the regular `Portfolio/...` route, then will_paginate will use Rails' `url_for` helper to generate the links with `Page/2` in them instead of `?page=2`. It's all about defining your routes and prioritizing them by reordering route definitions. Will_paginate doesn't actually generate any URLs; it leaves that to Rails routing.
