### ISSUE TITLE
make page an alias to paginate on arrays

### ISSUE THREAD

**Issue by gorn** [mislav/will_paginate#506]
Could you please make page an alias to paginate for Arrays? It is much easier to deal with the objects when the last thing in controller to do is to say 

      @collection.page(params[:page])

regardless the nature of @collection (Array or relation). Thanks

**Comment by mislav** [comment]
I can't make `page(num)` a method in `will_paginate/array` because then there's no way to pass a `:per_page` value. With Relation, it's possible with chaining:

```rb
relation.limit(30).page(1)
```

But the same syntax isn't possible with array. Therefore, you must call `array.paginate(...)` and pass all the parameters. Yes, I could make `array.page(1)` just use `WillPaginate.per_page` global setting, like `paginate()` does when you don't pass in `:per_page`, but I just don't think `array.page()` is a good API to be using.

Also, it's extremely easy to add yourself!

```rb
class Array
  def page(num)
    self.paginate(:page => num)
  end
end
```

**Comment by gorn** [comment]
Ok, it is your design choice - I would go with the :per_page from global setting, because I like to follow principle of least surprise, which I beleive is core principle of rails. However, you are right that I can easily add it myself. Thanks for your great work
