### ISSUE TITLE
Can we work on a v3.2.X without the support of ruby 1.X and rails 3.x ?

### ISSUE THREAD

**Issue by fwininger** [mislav/will_paginate#537]
I can do a PR to clean some old stuff if you agree to drop the support of old rails/ruby version ?

Sound something that you are ready to integrate ?

**Comment by mislav** [comment]
If we released a 3.2, there would have to be new features, and I don't have new features lined up for will_paginate right now. If the new release only dropped compatibility with older Ruby and older Rails, it wouldn't be compelling for people to upgrade, because it doesn't bring anything new.

Why would you drop compatibility with older versions?

**Comment by fwininger** [comment]
Thanks for the answer and the new release that fix deprecated warning.

It's just because, when a fix the unit test code, I see lot of exceptions in this repository to use deprecated code like `gem mysql` (https://github.com/luislavena/mysql-gem => unmaintained for 3 years). 
Ruby 1.X is unmaintained since 02/2015.
Rails 3.X is unmaintained for more than 1 years.

If you think that will_paginate should not move forward, you can close this issue.

**Comment by mislav** [comment]
We removed a lot of deprecations from the project recently.
