### ISSUE TITLE
"Will Paginate" string rendered instead of page gap separator - missing reasonable default

### ISSUE THREAD

**Issue by silverdr** [mislav/will_paginate#555]
`will_paginate-3.1.6` renders "Will Paginate" in the absence of `page_gap:` translation.

Actual result: as on the attached screenshot picture ("Will Paginate" string rendered)

Expected result: in the absence of translated string a reasonable default is rendered.

Screenshot:
![screen shot 2017-10-22 at 20 01 34](https://user-images.githubusercontent.com/4529686/31864834-038bf390-b765-11e7-9d85-037754118c36.png)

**Comment by mislav** [comment]
Hi, this is not possible with will_paginate out of the box, since the default behavior is to render the translation key for `will_paginate.page_gap`, with horizontal ellipsis (`…`) being the fallback in case of missing translation. The string "Will Paginate" must have come from the translation files in your application.

https://github.com/mislav/will_paginate/blob/ae522de8c4bf610a76475224fb401514e99be572/lib/will_paginate/view_helpers/link_renderer.rb#L56-L57

**Comment by silverdr** [comment]
Hi! It's been some time (and a few versions of `will_paginate`) but I'm quite sure I haven't had this kind of string in any of my translation files ;-) Anyway - if it falls back to horizontal ellipsis then it's exactly what I called "reasonable default" back then ;-)
